#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

IP="${1:-35.239.144.153}"
CERT_PATH="${2:-/etc/nginx/ssl/free-seo-tools/fullchain.pem}"
KEY_PATH="${3:-/etc/nginx/ssl/free-seo-tools/privkey.pem}"
MANIFEST_FILE="${4:-apps-manifests/apps.tsv}"

if [[ ! -f "$MANIFEST_FILE" ]]; then
  echo "Missing manifest: $MANIFEST_FILE" >&2
  exit 1
fi

cat <<EOF
# Generated by scripts/generate_host_https_ports_conf.sh
# One HTTPS listener per tool host port, each proxying to Docker gateway path routing.
# Example:
#   https://$IP:8101/ -> http://127.0.0.1:8000/ai-seo-pagescore/

EOF

while IFS=$'\t' read -r slug type host_port _internal_port; do
  if [[ -z "$slug" || "$type" == "unsupported" ]]; then
    continue
  fi

  cat <<EOF
server {
  listen ${host_port} ssl http2;
  server_name ${IP};

  ssl_certificate ${CERT_PATH};
  ssl_certificate_key ${KEY_PATH};

  location / {
    proxy_pass http://127.0.0.1:8000/${slug}/;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 120s;
  }
}

EOF
done < "$MANIFEST_FILE"
